"""Add password_hash column to Customer

Revision ID: 3c89d44a8736
Revises: 6b6d5e32ad75
Create Date: 2024-02-23 10:47:50.651466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c89d44a8736'
down_revision = '6b6d5e32ad75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column('customers', sa.Column('password_hash', sa.String(length=255), nullable=False, server_default=''), constraint_name='customers_password_hash')

        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
